### ISSUE TITLE
친구접속상태 어떻게 하는게 좋을지 논의 해주세요

### ISSUE THREAD

**Issue by Lee-Byung-Kyu** [42TransLand/ft_transcendence#16]
<img width="395" alt="image" src="https://user-images.githubusercontent.com/69182505/180910452-c9c1c61f-c669-4d7e-9a80-120a960582a5.png">
위 사진처럼 online/offline/In game 이런식으로 친구의 접속상태를 표시하기로 합의 했었는데,

<img width="794" alt="image" src="https://user-images.githubusercontent.com/69182505/180910713-27f6ed30-0fa7-4bd8-8cc2-7cac95631ad1.png">
차크라ui에서 다음과 같이 접속 상태 표현에 아주 찰떡인 뱃지기능을 제공하더라구요. 
이거 혹시 아래로 하는거 어떻게 생각하시는지 의견 좀 여쭙니다

**Comment by T2SU** [comment]
개쩐다

**Comment by T2SU** [comment]
빨리 바꾸죠 🙏

**Comment by JihoonNoahLee** [comment]
초록색 - 온라인
주황색 - 게임중
빨간색 - 오프라인 이런식으로 하면 될까요?

**Comment by JihoonNoahLee** [comment]
뭔가 바꾸는거보다 배지 + 텍스트 둘 다 있으면 좋지 않을까 하는 생각도 드네요

**Comment by JihoonNoahLee** [comment]
그치만 바꾸는게 제일 안귀찮고 좋을듯

**Comment by Lee-Byung-Kyu** [comment]
의견 잘 들었습니다.
