### ISSUE TITLE
게임에서 나왔는데 게임중으로 보임

### ISSUE THREAD

**Issue by Lee-Byung-Kyu** [42TransLand/ft_transcendence#211]
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/69182505/185558882-0abe27c2-a84b-4948-bf1b-bcf0e0851ac9.png">

1. 게임 방을 먼저 들어간 사람이 먼저 나오는 경우 상대방의 입장에서 상태가 제대로 반영이 안되는 것을 확인.

2. 게임 방을 먼저 들어간 사람이 나중에 나오면 문제 없음.

3. 커스텀 게임도 래더 게임과 동일한 현상 발생

**Comment by Lee-Byung-Kyu** [comment]
왼쪽이 게임 만든 사람, 게임 이긴 사람, 게임 룸에서 먼저 나온 사람

**Comment by T2SU** [comment]
https://github.com/42TransLand/ft_transcendence/pull/213
