### ISSUE TITLE
업데이트 멤버인데 하는 일은 인서트 멤버에 가깝다.

### ISSUE THREAD

**Issue by Lee-Byung-Kyu** [42TransLand/ft_transcendence#72]
업데이트 멤버인데 하는 일은 인서트 멤버에 가깝다.

_Originally posted by @Lee-Byung-Kyu in https://github.com/42TransLand/ft_transcendence/pull/71#discussion_r937245302_

**Comment by T2SU** [comment]
수정했습니다. (https://github.com/42TransLand/ft_transcendence/pull/73/commits/c52f59f8d6a444de5d9f69c015a15913ea26d341)
